
# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial?srsltid=AfmBOoppDqtkhRxj5BLZONRZFzRDmh6eP-xyTo6H4OuEHYuVbrg1d4Dm


# Requests for API endpoints of the sample project:

### Hello world endpoint: get response "Hello, Stranger!"
GET http://localhost:8080/hello-world

### Hello world with a request param passed.
# When sending the request it will ask you for the name
# hitting enter will avoid passing the param, and do the default behaviour above
# @prompt name The name to display in response
GET http://localhost:8080/hello-world
    ?name={{name}}

### Save a greeting to database
@postGreetingId = 1001
@postGreetingContent = Hello!
POST http://localhost:8080/greetings
Content-Type: application/json

{
    "id": "{{postGreetingId}}",
    "content": "{{postGreetingContent}}"
}

### Get all greetings
GET http://localhost:8080/greetings

### Get info for greeting with given content
# @prompt content Greeting content to look for, defaults to "Overview"
GET http://localhost:8080/info
    ?title={{content}}

### Update an existing greeting
@putGreetingId = 1001
@putGreetingContent = Hello again!
PUT http://localhost:8080/greetings/{{putGreetingId}}
Content-Type: application/json

{
    "content": "{{putGreetingContent}}"
}

### Delete greeting
@deleteGreetingId = 1001
DELETE http://localhost:8080/greetings/{{deleteGreetingId}}


# TODO add requests for your own endpoints!

### Inregistreaza un utilizator nou
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "testuserv5",
    "email": "testv5@example.com",
    "password": "testpasswordv5"
}

### Autentificare utilizator
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "testuserv5",
    "password": "testpasswordv5"
}

### Obtine lista tuturor utilizatorilor
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcnY0IiwiaWF0IjoxNzQyMTM2MTc1LCJleHAiOjE3NDIyMjI1NzV9.vefpJJyS9wHoOODeSSGw0t1Wc_ZqqLTw6_ZQDRazffM

### Obtine informatii despre un utilizator
GET http://localhost:8080/api/users/testuserv4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcnY0IiwiaWF0IjoxNzQyMTM2MTc1LCJleHAiOjE3NDIyMjI1NzV9.vefpJJyS9wHoOODeSSGw0t1Wc_ZqqLTw6_ZQDRazffM

### Sterge un utilizator
DELETE http://localhost:8080/api/users/testuser
